### ISSUE TITLE
Chocolatey package

### ISSUE THREAD

**Issue by alexchandel** [alirdn/windows-kill#1]
Would you consider building this and uploading it as a [chocolatey](https://chocolatey.org/) package?

**Comment by alirdn** [comment]
Good suggestion. I'll work on it and add it as a chocolatey package in next couple days.

**Comment by alirdn** [comment]
@alexchandel I added the package to chocolatey. It's waiting for approval from a moderator. When approved, I will add the chocolatey package as the main way of installation to README.

**Comment by gep13** [comment]
@alirdn thank you for submitting this Chocolatey Package.  It has now been approved. 👍

**Comment by alirdn** [comment]
@gep13 you're welcome. Thank you too.
